# Generated by Django 6.0.2 on 2026-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=1, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
