# Generated by Django 6.0.2 on 2026-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
