# Generated by Django 6.0.2 on 2026-03-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
