# Generated by Django 6.0.2 on 2026-04-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
