# Generated by Django 6.0.2 on 2026-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
